"""Add architecture_analysis and refactor_suggestions tables

Revision ID: 43b75e9306d3
Revises: f82fe7d73cd2
Create Date: 2026-03-05 21:11:55.377143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43b75e9306d3'
down_revision: Union[str, None] = 'f82fe7d73cd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
