"""init

Revision ID: 9d778599cd02
Revises: 
Create Date: 2026-03-03 12:08:34.269997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d778599cd02'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('analysis', 'score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_analysis_repo_id'), 'analysis', ['repo_id'], unique=False)
    op.add_column('issues', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('issues', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # Create severity enum type explicitly for PostgreSQL
    severity_enum = sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity')
    severity_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column('issues', 'severity',
               existing_type=sa.VARCHAR(length=20),
               type_=severity_enum,
               postgresql_using="severity::severity",
               existing_nullable=False)
    op.create_index(op.f('ix_issues_analysis_id'), 'issues', ['analysis_id'], unique=False)
    op.add_column('metrics', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('metrics', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_metrics_analysis_id'), 'metrics', ['analysis_id'], unique=False)
    op.add_column('repositories', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('repositories', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_repositories_user_id'), 'repositories', ['user_id'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.add_column('users', sa.Column('avatar_url', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('access_token', sa.String(length=255), nullable=False))
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_unique_constraint(None, 'users', ['access_token'])
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_column('users', 'access_token')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'avatar_url')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_repositories_user_id'), table_name='repositories')
    op.drop_column('repositories', 'updated_at')
    op.drop_column('repositories', 'created_at')
    op.drop_index(op.f('ix_metrics_analysis_id'), table_name='metrics')
    op.drop_column('metrics', 'updated_at')
    op.drop_column('metrics', 'created_at')
    op.drop_index(op.f('ix_issues_analysis_id'), table_name='issues')
    op.alter_column('issues', 'severity',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('issues', 'updated_at')
    op.drop_column('issues', 'created_at')
    op.drop_index(op.f('ix_analysis_repo_id'), table_name='analysis')
    op.alter_column('analysis', 'score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('analysis', 'updated_at')
    # ### end Alembic commands ###
