"""Add metrics model and analysis_type

Revision ID: f82fe7d73cd2
Revises: 9d778599cd02
Create Date: 2026-03-05 20:43:23.997697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f82fe7d73cd2'
down_revision: Union[str, None] = '9d778599cd02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
